import type { ScanResult, NutrientScores } from '@/types/scores';
import type { Scan } from '@/types/scan';

export const MOCK_NUTRIENT_SCORES: NutrientScores = {
  ironSupport: {
    score: 58,
    status: 'Moderate',
    explanation:
      'Your iron support pattern appears moderate. Leafy greens and legume intake could be improved for better support.',
  },
  vitaminB12Support: {
    score: 72,
    status: 'Balanced',
    explanation:
      'B12 intake sources appear present in your diet. Dairy and egg consumption contribute positively.',
  },
  vitaminDSupport: {
    score: 42,
    status: 'Needs Attention',
    explanation:
      'Limited sunlight exposure combined with dietary patterns suggests this area may benefit from attention.',
  },
  folateSupport: {
    score: 65,
    status: 'Balanced',
    explanation:
      'Folate support appears balanced. Regular green vegetable intake helps maintain this pattern.',
  },
  proteinSupport: {
    score: 78,
    status: 'Balanced',
    explanation:
      'Protein intake appears well-supported through your mixed dietary pattern and regular meals.',
  },
  hydrationSupport: {
    score: 55,
    status: 'Moderate',
    explanation:
      'Daily water intake could be improved. Consider increasing fluid consumption especially during active days.',
  },
  dietQualitySupport: {
    score: 68,
    status: 'Balanced',
    explanation:
      'Overall diet quality appears reasonable with room for improvement in variety and consistency.',
  },
  vitaminASupport: {
    score: 70,
    status: 'Balanced',
    explanation: 'Vitamin A intake appears adequate from dietary sources. Eye and skin markers look healthy.',
  },
  zincSupport: {
    score: 62,
    status: 'Moderate',
    explanation: 'Zinc intake is borderline. Consider adding seeds, nuts, and legumes for better support.',
  },
  vitaminCSupport: {
    score: 74,
    status: 'Balanced',
    explanation: 'Vitamin C from fruits and vegetables appears reasonable in current diet pattern.',
  },
  omega3Support: {
    score: 48,
    status: 'Needs Attention',
    explanation: 'Omega-3 sources appear limited. Adding flaxseeds, walnuts, or fish could improve this.',
  },
};

export const MOCK_SCAN_RESULT: ScanResult = {
  overallBalanceScore: 64,
  nutrientScores: MOCK_NUTRIENT_SCORES,
  focusAreas: [
    {
      nutrient: 'vitaminDSupport',
      title: 'Vitamin D Support',
      description:
        'Consider increasing natural sunlight exposure (15-20 min daily) and including vitamin D-rich foods like fortified milk, mushrooms, or fatty fish.',
      priority: 'high',
    },
    {
      nutrient: 'hydrationSupport',
      title: 'Hydration Pattern',
      description:
        'Try to drink water more consistently throughout the day. Carrying a water bottle and setting reminders can help build the habit.',
      priority: 'medium',
    },
    {
      nutrient: 'ironSupport',
      title: 'Iron Support',
      description:
        'Consider pairing iron-rich foods with vitamin C sources for better absorption. Spinach, lentils, and fortified cereals are solid choices.',
      priority: 'medium',
    },
  ],
  recommendations: [
    {
      id: 'r1',
      category: 'food',
      title: 'Add leafy greens daily',
      description: 'Spinach, kale, or methi in at least one meal supports iron and folate.',
      icon: 'leaf',
    },
    {
      id: 'r2',
      category: 'food',
      title: 'Include citrus with meals',
      description: 'Vitamin C helps iron absorption — try lemon on salads or an orange after meals.',
      icon: 'citrus',
    },
    {
      id: 'r3',
      category: 'habit',
      title: 'Morning sunlight routine',
      description: '15-20 minutes of morning sunlight supports vitamin D and circadian rhythm.',
      icon: 'sun',
    },
    {
      id: 'r4',
      category: 'habit',
      title: 'Hydration tracking',
      description: 'Aim for 8 glasses of water daily. Start with a glass first thing in the morning.',
      icon: 'droplet',
    },
    {
      id: 'r5',
      category: 'lifestyle',
      title: 'Consistent meal timing',
      description: 'Eating at regular times helps nutrient absorption and energy stability.',
      icon: 'clock',
    },
    {
      id: 'r6',
      category: 'food',
      title: 'Nuts and seeds snack',
      description: 'A handful of almonds, walnuts, or pumpkin seeds adds protein, iron, and healthy fats.',
      icon: 'wheat',
    },
  ],
  confidenceNote:
    'This insight is generated by Norla using AI-powered pattern analysis of your uploaded images and questionnaire responses. These are predicted wellness support scores — not clinical diagnoses or lab measurements. For medical advice, always consult a qualified healthcare professional.',
};

export const MOCK_SCAN_HISTORY: Scan[] = [
  {
    id: 'scan-demo-1',
    userId: 'demo-user',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'completed',
    images: { faceImageUrl: '', eyeImageUrl: '', handImageUrl: '' },
    questionnaire: {
      energyLevel: 3, sleepQuality: 4, dailyWaterIntake: 3, sunlightExposure: 2,
      foodPattern: 'mixed', eggFrequency: 'sometimes', dairyFrequency: 'often',
      leafyGreensFrequency: 'sometimes', legumesFrequency: 'sometimes', meatFrequency: 'rarely',
      mealRegularity: 4, exerciseLevel: 3, hairFall: false, skinDullness: true,
      weakness: false, concentrationIssues: false, appetite: 4, stressLevel: 2,
    },
    overallBalanceScore: 64,
    nutrientScores: MOCK_NUTRIENT_SCORES,
    focusAreas: MOCK_SCAN_RESULT.focusAreas,
    recommendations: MOCK_SCAN_RESULT.recommendations,
    confidenceNote: MOCK_SCAN_RESULT.confidenceNote,
  },
  {
    id: 'scan-demo-2',
    userId: 'demo-user',
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'completed',
    images: { faceImageUrl: '', eyeImageUrl: '', handImageUrl: '' },
    questionnaire: {
      energyLevel: 2, sleepQuality: 3, dailyWaterIntake: 2, sunlightExposure: 1,
      foodPattern: 'vegetarian', eggFrequency: 'rarely', dairyFrequency: 'sometimes',
      leafyGreensFrequency: 'rarely', legumesFrequency: 'sometimes', meatFrequency: 'never',
      mealRegularity: 2, exerciseLevel: 2, hairFall: true, skinDullness: true,
      weakness: true, concentrationIssues: true, appetite: 2, stressLevel: 4,
    },
    overallBalanceScore: 48,
    nutrientScores: {
      ironSupport: { score: 38, status: 'Needs Attention', explanation: 'Iron support appears low based on dietary patterns and symptoms.' },
      vitaminB12Support: { score: 35, status: 'Needs Attention', explanation: 'B12 sources appear limited in a vegetarian pattern without supplementation.' },
      vitaminDSupport: { score: 28, status: 'Low Support', explanation: 'Very limited sunlight exposure suggests vitamin D support is low.' },
      folateSupport: { score: 52, status: 'Moderate', explanation: 'Some folate sources present but inconsistent green vegetable intake.' },
      proteinSupport: { score: 55, status: 'Moderate', explanation: 'Plant-based protein sources could be increased for better support.' },
      hydrationSupport: { score: 40, status: 'Needs Attention', explanation: 'Water intake appears insufficient for daily needs.' },
      dietQualitySupport: { score: 45, status: 'Needs Attention', explanation: 'Irregular meals and limited variety affect overall diet quality.' },
      vitaminASupport: { score: 45, status: 'Needs Attention', explanation: 'Limited vegetable variety reduces vitamin A support.' },
      zincSupport: { score: 42, status: 'Needs Attention', explanation: 'Zinc sources limited in vegetarian diet without adequate legumes.' },
      vitaminCSupport: { score: 50, status: 'Moderate', explanation: 'Some fruit intake but inconsistent for optimal vitamin C levels.' },
      omega3Support: { score: 32, status: 'Low Support', explanation: 'Very limited omega-3 sources in current dietary pattern.' },
    },
    focusAreas: MOCK_SCAN_RESULT.focusAreas,
    recommendations: MOCK_SCAN_RESULT.recommendations,
    confidenceNote: MOCK_SCAN_RESULT.confidenceNote,
  },
];
