import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service — Norla',
  description: 'Terms and conditions for using the Norla nutrition insight application.',
};

export default function TermsOfServicePage() {
  const lastUpdated = 'April 14, 2025';
  const contactEmail = process.env.NEXT_PUBLIC_CONTACT_EMAIL || 'support@norla.app';
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://norla.app';

  return (
    <div className="min-h-screen bg-white" style={{ fontFamily: 'Inter, -apple-system, sans-serif' }}>
      {/* Header */}
      <div className="border-b border-neutral-100 px-6 py-4">
        <div className="max-w-2xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <img src="/logo.png" alt="Norla" className="h-8 w-8 object-contain" />
            <span className="text-[16px] font-bold text-neutral-900">Norla</span>
          </Link>
          <Link href="/privacy" className="text-[13px] text-neutral-500 hover:text-neutral-700">
            Privacy Policy →
          </Link>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-2xl mx-auto px-6 py-12">
        <h1 className="text-[32px] font-bold text-neutral-900 tracking-tight mb-2">Terms of Service</h1>
        <p className="text-[13px] text-neutral-400 mb-10">Last updated: {lastUpdated}</p>

        <div className="space-y-8 text-[14px] text-neutral-700 leading-[1.8]">

          <section>
            <p className="p-4 bg-amber-50 rounded-xl text-[13px] text-amber-800 border border-amber-100 font-medium">
              ⚠️ <strong>Important:</strong> Norla provides AI-powered wellness insights for informational purposes only.
              It is NOT a medical device, NOT a clinical diagnostic tool, and does NOT replace professional medical advice.
              Always consult a qualified healthcare professional before making health decisions.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-bold text-neutral-900 mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Norla at <a href={appUrl} className="text-teal-600 underline">{appUrl}</a> or
              through our mobile application, you agree to be bound by these Terms of Service. If you do not agree
              to these terms, please do not use our service.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-bold text-neutral-900 mb-3">2. Description of Service</h2>
            <p>
              Norla uses artificial intelligence to analyze photographs of your face, eyes, and hands along with
              lifestyle questionnaire responses to generate &ldquo;predicted nutrition support scores.&rdquo;
              These scores represent AI-generated estimates of potential nutritional patterns — they are not
              laboratory measurements, clinical assessments, or medical diagnoses.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-bold text-neutral-900 mb-3">3. Eligibility</h2>
            <ul className="list-disc list-inside space-y-1 text-neutral-600">
              <li>You must be at least 13 years of age to use Norla</li>
              <li>If you are under 18, you must have parental or guardian consent</li>
              <li>You must provide accurate information during registration</li>
            </ul>
          </section>

          <section>
            <h2 className="text-[18px] font-bold text-neutral-900 mb-3">4. Medical Disclaimer</h2>
            <p>
              <strong>Norla is not a substitute for professional medical advice, diagnosis, or treatment.</strong>
              The nutrition scores, focus areas, and recommendations provided by Norla:
            </p>
            <ul className="list-disc list-inside space-y-1 text-neutral-600 mt-2">
              <li>Are generated by AI and may not be accurate</li>
              <li>Are for general wellness awareness only</li>
              <li>Should not be used to self-diagnose any health condition</li>
              <li>Should not replace consultation with a qualified health professional</li>
              <li>Should not be used to start, stop, or change any medical treatment</li>
            </ul>
          </section>

          <section>
            <h2 className="text-[18px] font-bold text-neutral-900 mb-3">5. User Responsibilities</h2>
            <p>You agree to:</p>
            <ul className="list-disc list-inside space-y-1 text-neutral-600 mt-2">
              <li>Use Norla only for personal, non-commercial purposes</li>
              <li>Provide only your own photos (not photos of other people)</li>
              <li>Not use the service to harm yourself or others</li>
              <li>Maintain the security of your account</li>
              <li>Not attempt to reverse-engineer the AI model or the application</li>
              <li>Not use automated tools to access the service in bulk</li>
            </ul>
          </section>

          <section>
            <h2 className="text-[18px] font-bold text-neutral-900 mb-3">6. Intellectual Property</h2>
            <p>
              All content within the Norla application — including the AI model outputs, scoring algorithms,
              design, and branding — is the intellectual property of Norla. You retain ownership of the photos
              and information you submit. You grant Norla a limited license to process your submitted data to
              provide the service.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-bold text-neutral-900 mb-3">7. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable law, Norla and its operators shall not be liable for:
            </p>
            <ul className="list-disc list-inside space-y-1 text-neutral-600 mt-2">
              <li>Any health outcomes resulting from reliance on Norla&apos;s insights</li>
              <li>Inaccurate AI-generated nutrition scores</li>
              <li>Loss of data due to technical failures</li>
              <li>Indirect, incidental, or consequential damages</li>
            </ul>
          </section>

          <section>
            <h2 className="text-[18px] font-bold text-neutral-900 mb-3">8. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to Norla at any time if you violate
              these Terms of Service. You may also delete your account at any time from the Profile section
              of the app.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-bold text-neutral-900 mb-3">9. Changes to Terms</h2>
            <p>
              We may modify these Terms of Service at any time. Continued use of the service after changes
              are posted constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-bold text-neutral-900 mb-3">10. Governing Law</h2>
            <p>
              These Terms shall be governed by the laws of India. Any disputes arising shall be subject to
              the exclusive jurisdiction of the courts in India.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-bold text-neutral-900 mb-3">11. Contact</h2>
            <div className="mt-3 p-4 bg-neutral-50 rounded-xl text-[13px]" style={{ border: '1px solid rgba(0,0,0,0.06)' }}>
              <p><strong>Norla Support</strong></p>
              <p>Email: <a href={`mailto:${contactEmail}`} className="text-teal-600 underline">{contactEmail}</a></p>
            </div>
          </section>

        </div>
      </div>

      {/* Footer */}
      <div className="border-t border-neutral-100 py-6 text-center">
        <div className="flex items-center justify-center gap-4 text-[12px] text-neutral-400">
          <Link href="/" className="hover:text-neutral-600">Home</Link>
          <Link href="/privacy" className="hover:text-neutral-600">Privacy Policy</Link>
          <span>© {new Date().getFullYear()} Norla. All rights reserved.</span>
        </div>
      </div>
    </div>
  );
}
